services:
  serena:
    image: ghcr.io/oraios/serena:latest
    # container_name は指定しない（重要！）
    
    command: >
      serena start-mcp-server
      --transport streamable-http
      --port 9121
      --host 0.0.0.0
      --enable-web-dashboard False
      --project /workspaces/project
    
    volumes:
      - ./.serena_home:/root/.serena
      - .:/workspaces/project
    
    expose:
      - "9121"
